[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gymnasium_qr"]

[project]
name = "gymnasium_qr"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "pygame>=2.1.3",
  "Box2D>=2.3.10",
  "pre-commit",
]
